### ISSUE TITLE
Prevent teams with the same name

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#103]
## Expected Behavior
Each team should has it's own unique name
## Actual Behavior
You can create teams with the same name
## Solution
add to the team model :
name = models.CharField(max_length=255, blank=False, unique=True)

**Comment by orzionpour** [comment]
Should tests be included here? I'm not sure because "unique=True" one of Django's features

**Comment by AvivLiberman** [comment]
We need to add the team's name unique the default was only on the ID

**Comment by orzionpour** [comment]
I have it ready, waiting for #88 to be merged.
