### ISSUE TITLE
Add tasks filters features

### ISSUE THREAD

**Issue by orzionpour** [redhat-beyond/falcon#104]
First, note it is related to #93, #94 .

After creating the default user view, there should be added 2 filters:

- [ ] Filter by status
- [x] Filter by priority

Feel free to add any filter you think is relevant.

**Comment by Asafh7** [comment]
I'm on it

**Comment by orzionpour** [comment]
#129 fixes the priority filter.
status filter was diverged to issue [#136](https://github.com/redhat-beyond/falcon/issues/136)
