### ISSUE TITLE
Fix urls redirect flow

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#106]
## Expected Behavior

- Homepage should be the first page you are landing on
- As Manager you should see New Task button
- As Employee you should not see New Task button

## Actual Behavior
Home page is not the first page, employee sees the New Task button

**Comment by orzionpour** [comment]
I have ready the last 2

**Comment by avraham1992** [comment]
@orzionpour Yes, it's a pity you did not register that you talked to me ..
