### ISSUE TITLE
Add clean filter button to be able to see all the results without filter

### ISSUE THREAD

**Issue by kobihk** [redhat-beyond/falcon#150]
## Expected Behavior
Add "clean filter" button to be able to see all the results without filter

## Actual Behavior
After running filter to see only tasks with Low priority 
then if I want to see back all tasks without a filter I have to click on View Tasks which is less intuitive. 

## Steps to Reproduce the Problem

1. Login as User
2. Click on Tasks 
2. Filter tasks with Low priority

**Comment by orzionpour** [comment]
I guess that if @Asafh7 will change the HTML from `Select a status` and `Select a status` to `All` on #149, we can get that functionality.
@kobihk Let us know you think it's a reasonable solution (I'm pretty sure it'll work, didn't check it yet).

**Comment by kobihk** [comment]
@orzionpour @Asafh7 
Yes, it could be good enough if we will have the option of All - which is the same as clean of the current filter.
