### ISSUE TITLE
CI fails with flake8 warnings

### ISSUE THREAD

**Issue by nunnatsa** [redhat-beyond/falcon#17]
After adding flake8 check in the CI, this check is fails for several syntax errors in existing files.

```
./falcon/urls.py:23:19: E203 whitespace before ','
./falcon/urls.py:23:20: E231 missing whitespace after ','
./falcon/views.py:3:1: E302 expected 2 blank lines, found 1
./falcon/views.py:4:41: W292 no newline at end of file
```

**Comment by avraham1992** [comment]
Maybe the problem with flake8?
Because everything worked before

**Comment by nunnatsa** [comment]
No, these are real flake8 warnings. I'm getting the same in my local repository. The fix is pretty simple.

**Comment by AvivLiberman** [comment]
https://github.com/redhat-beyond/falcon/pull/22
