### ISSUE TITLE
Merge 'static' and 'Resources' folders

### ISSUE THREAD

**Issue by orzionpour** [redhat-beyond/falcon#18]
Merge 'static' and 'Resources' folders
Update paths in relevant files (like the logo image, etc...)

**Comment by AvivLiberman** [comment]
@orzionpour can you close this issue?

**Comment by orzionpour** [comment]
Closed.

**Comment by orzionpour** [comment]
Will be closed after #35 is merged.
Or just add `Resolves #18` to #35 description
