### ISSUE TITLE
Adding Login page

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#24]
Move the login page to the users app.
- [ ] create templates folder for the users app
- [ ] moving login page to users app
- [ ] configure login page url to /login
- [ ] add homepage in falcon templates

Check out https://github.com/AvivLiberman/falcon/tree/new-login-page for nice and clean CSS and HTML if you want to 😉

**Comment by AvivLiberman** [comment]
@orzionpour after #35 is done you can take care of this?

**Comment by orzionpour** [comment]
Will be my pleasure 🙃

**Comment by AvivLiberman** [comment]
@orzionpour got any progress?
I think you should also route the login page to /login and create new home page separately

**Comment by orzionpour** [comment]
Not yet, due to time limits..
I will work on it after Tuesday’s Midterm, with hope that I will finish by Wednesday.
Sorry for the delay.
And yes - as Barak’s suggested after the first demo, I will implement a proper landing page in addition to the login page.
