### ISSUE TITLE
Adding model diagram to the README

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#39]
Adding this [link](https://drawsql.app/idc-1/diagrams/falcon) to the README.

**Comment by AvivLiberman** [comment]
@Asafh7 can you please take care of it?

**Comment by Asafh7** [comment]
yes, but I have this problem : remote: Permission to redhat-beyond/falcon.git denied to Asafh7.
seems like I don't have permission to push.
