### ISSUE TITLE
Open a team for all contributors for falcon app

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#40]
Hey to make it easier to mention everyone here to code review. Can you please create us some group for that? or any automation that put us all as reviewers for the PRs?

@mgold1234 @natifridman @kobihk @nunnatsa

**Comment by kobihk** [comment]
IMHO when you add a group instead of specific persons it is less effective than to ask them literally

**Comment by nunnatsa** [comment]
Hi @AvivLiberman. Adding a user to github team means to add them to the github organization. This is not what we want, but to only add users to the specific repo.

I added all of you to this repo.
