### ISSUE TITLE
Adding some CI

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#7]
- [ ] Install Flake8
- [ ] Add GitHub actions configuration

**Comment by AvivLiberman** [comment]
@avraham_chababo Can you take care of it?

**Comment by avraham1992** [comment]
Do not know what the problem is he tells me he does not recognize the command .. all files exist I sat on it tomorrow at noon again

**Comment by orzionpour** [comment]
https://github.com/redhat-beyond/falcon/pull/12

**Comment by orzionpour** [comment]
Resolved in #15
