### ISSUE TITLE
Change repository merging to be Squash and Merge

### ISSUE THREAD

**Issue by AvivLiberman** [redhat-beyond/falcon#80]
## Expected Behavior
Only one commit on main branch for each PR

## Actual Behavior
After merging PR all the commits stays

## Solution
In the settings of this repository ***change the default*** for merging PR to be ***Squash and Merge***.
After we submit a PR (which will be only one commit) we continue to push commits (and not rebase) so you can see the flow of work and not destroy the comments (force push messing up the comments).

Can you please change it in the settings?
@kobihk @natifridman @mgold1234 @nunnatsa

**Comment by mgold1234** [comment]
![image](https://user-images.githubusercontent.com/73419853/143675519-d6734e8c-ac48-40ff-af89-44e2748531f9.png)
uncheck 'allow merge commits' and 'allow rebase merging'
